# ---
# title:  alacritty configuration file
# author: emil lenz
# email:  emillenz@protonmail.com
# date:   [2022-02-25] (monochrome theme: [2024-12-15]
# info:
# - monochrome theme to make the terminal experience more minimal and focused.
# ---

[cursor]
unfocused_hollow = false

[env]
WINIT_X11_SCALE_FACTOR = "1" # same fontsize across different dpi displays

[font]
normal = {family = "Iosevka Comfy"}
size = 10

[mouse]
hide_when_typing = true

[window]
decorations = "full"
dynamic_padding = true
dynamic_title = true
startup_mode = "Maximized"
opacity = 1.0

# MODUS OPERANDI THEME
[colors]
transparent_background_colors = false

[colors.primary]
background = "#ffffff"
foreground = "#000000"

[colors.normal]
black =   "#000000"
red =     "#000000"
green =   "#000000"
yellow =  "#000000"
blue =    "#000000"
magenta = "#000000"
cyan =    "#000000"
white =   "#ffffff"

[colors.cursor]
cursor     = "#000000"
text       = "#ffffff"

[colors.vi_mode_cursor]
cursor     = "#000000"
text       = "#ffffff"

[colors.selection]
background = "CellForeground"
text       = "CellBackground"
