# ---
# title:  alacritty configuration file
# author: emil lenz
# email:  emillenz@protonmail.com
# date:   2022-02-25
# info:   minimal, coinsistent and fast config
# ---

import = ["~/.config/alacritty/modus_operandi.toml"]
ipc_socket = true
live_config_reload = true
working_directory = "None"

[cursor]
unfocused_hollow = false
vi_mode_style = "Block"

[env]
WINIT_X11_SCALE_FACTOR = "1" # NOTE :: same fontsize across different dpi displays

[font]
normal = {family = "Iosevka Comfy"}
size = 10.5

[mouse]
hide_when_typing = true

[scrolling]
multiplier = 10

[selection]
save_to_clipboard = true

[shell]
program = "/usr/bin/fish"
args = ["--login"]

[window]
decorations = "full"
dynamic_padding = true
dynamic_title = true
startup_mode = "Maximized"
opacity = 1.0
