modmap:
  - name: global
    remap:
       # when user has mapped caps->backspace on keyboard-hardware
      backspace:
        held: super_l
        alone: backspace
        one_timeout_milis: 100

      capslock: 
        held: super_l
        alone: backspace
        one_timeout_milis: 100
      
keymap:
  - name: browser
    application:
      not: [Emacs, Alacritty]
    remap:
      M-backspace: C-backspace # consistency with emacs
      C-n: down # completion candidates (suggested urls ...)
      C-p: up
