# ---
# title:  alacritty configuration file
# author: emil lenz
# email:  emillenz@protonmail.com
# date:   2022-02-25
# info:
# - i disable all: {tabs, scrollback, clipboard integration} keybindings, since this is already handled by the terminal multiplexer (tmux).  we don't want duplicate functionality.
# - all i need from a terminal is to be blazingly fast
# ---

[cursor]
unfocused_hollow = false

[env]
WINIT_X11_SCALE_FACTOR = "1" # same fontsize across different dpi displays

[font]
normal = {family = "Iosevka Comfy"}
size = 10

[mouse]
hide_when_typing = true

[window]
decorations = "full"
dynamic_padding = true
dynamic_title = true
startup_mode = "Maximized"
opacity = 1.0

# MODUS OPERANDI THEME
[colors]
transparent_background_colors = false

[colors.primary]
background = "#ffffff"
foreground = "#000000"

[colors.normal]
black =   "#000000"
red =     "#a60000"
green =   "#006800"
yellow =  "#6f5500"
blue =    "#0031a9"
magenta = "#721045"
cyan =    "#005e8b"
white =   "#a6a6a6"

[colors.bright]
black =   "#595959"
red =     "#972500"
green =   "#00663f"
yellow =  "#884900"
blue =    "#3548cf"
magenta = "#531ab6"
cyan =    "#005f5f"
white =   "#ffffff"

[colors.cursor]
cursor     = "#000000"
text       = "#ffffff"

[colors.vi_mode_cursor]
cursor     = "#000000"
text       = "#ffffff"

[colors.selection]
background = "CellForeground"
text       = "CellBackground"
