# ---
# title:  config
# author: emil lenz
# email:  emillenz@protonmail.com
# date:   2024-01-18
# info:   gtk apps are configured to use readline bindings already (gtk-emacs-keytheme)
#         if you are on a different linux machine, use gnome-tweak-tools and: `setxkbmap -option ctrl:nocaps` to get basically the same effect.
# ---

modmap:
  - name: global
    remap:
      capslock:
        held: ctrl_l
        alone: esc
        one_timeout_milis: 100
      ctrl_l: # hack :: support physical ctrl -> caps remaps
        held: ctrl_l
        alone: esc
        one_timeout_milis: 100

keymap:
  - name: browser
    application:
      only: firefox
    remap:
      C-n: down # vim :: navigate completion candidates
      C-p: up
