# ---
# title:  config
# author: emil lenz
# email:  emillenz@protonmail.com
# date:   2024-01-18
# info:   gtk apps are configured to use readline bindings already (gtk-emacs-keytheme)
#         if you are on a different linux machine, use gnome-tweak-tools and: `setxkbmap -option ctrl:nocaps` to get basically the same effect.
# ---

modmap:
  - name: global
    remap:
      capslock:
        held: ctrl_l
        alone: esc
        one_timeout_milis: 100
      ctrl_l: # hack :: support physical ctrl -> caps remaps
        held: ctrl_l
        alone: esc
        one_timeout_milis: 100

keymap:
  # implementing a rudimentary vim layer for input prompt navigation.
  - name: browser
    application:
      only: firefox
    remap:
      C-n: down
      C-p: up

      C-q: c-w # close tab
      C-semicolon: c-l # focus address bar

      C-j: down
      C-k: up
      C-l: right
      C-shift-h: left # conflict with backspace

      C-w: c-backspace
      C-h: backspace
      C-u: [shift-home, delete] # kill backward to start of line

      C-e: c-right
      C-b: c-left

      C-a: end # vim: A
      C-i: home # vim: I

      C-x: delete
      C-d: c-delete
